### ISSUE TITLE
Please add PSR-7 request support

### ISSUE THREAD

**Issue by Big-Shark** [railt/http#1]

**Comment by SerafimArts** [comment]
Need to implement the psr-7 interface for the basic query:
 
- [RequestInterface](
 https://github.com/railt/http/blob/054d47b779e06291e964965478d7a32a0e63bfcc/src/RequestInterface.php)
Or add the ability to process them:
- [Adapters](https://github.com/railt/http/blob/054d47b779e06291e964965478d7a32a0e63bfcc/src/Request.php#L27-L30
)
?
